#!/bin/sh
function usage (){
  echo "usage: chroot-to [options] directory"
  echo "  directory: the root directory"
  echo "  options:"
  echo "    -s --shell shell, default: /bin/bash"
  echo "       --help usage"
  exit
}
GETOPT_ARGS=`getopt -o s:h -l shell:,help -- "$@"`
eval set -- ${GETOPT_ARGS}

ROOT_DIR=""
SHELL_BIN=""

while [ ${1} ]
do
  case ${1} in
    -s|--shell) SHELL_BIN=${2};shift 2; continue;;
    --) shift 1; ROOT_DIR=${1}; shift 1; continue;;
    -h|--help|*) usage;;
  esac
done

if [[ ! -n ${SHELL_BIN} ]]
then
  SHELL_BIN=/bin/bash
fi

if [[ ! -n ${ROOT_DIR} ]]
then
  usage
fi
ROOT_DIR=$(realpath ${ROOT_DIR})

mount -t proc proc ${ROOT_DIR}/proc
mount --rbind /sys ${ROOT_DIR}/sys
mount --make-rslave ${ROOT_DIR}/sys
mount --rbind /dev ${ROOT_DIR}/dev
mount --make-rslave ${ROOT_DIR}/dev
mount --rbind /run ${ROOT_DIR}/run
mount --make-rslave ${ROOT_DIR}/run
mount --rbind /tmp ${ROOT_DIR}/tmp
mount --make-rslave ${ROOT_DIR}/tmp
chroot ${ROOT_DIR}/ ${SHELL_BIN}
